# Generated by Django 4.1.7 on 2023-03-08 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='Enter more than 10 values')])),
                ('twitter_handle', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
