# Generated by Django 4.1.7 on 2023-03-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_rename_friends_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='twitter_handle',
            field=models.CharField(max_length=100),
        ),
    ]
