# Generated by Django 4.1.7 on 2023-03-12 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friend_twitter_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='email',
            field=models.CharField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='friend',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='Enter more than 10 values')]),
        ),
    ]
