# Generated by Django 4.1.7 on 2023-03-12 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_alter_friend_email_alter_friend_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='email',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='friend',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='Enter more than 10 values')]),
        ),
        migrations.AlterField(
            model_name='friend',
            name='twitter_handle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
